"""Comments

Revision ID: e9d6e8290c3c
Revises: 
Create Date: 2025-09-10 10:25:26.365373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9d6e8290c3c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupon_redemptions', sa.Column('bogo_free_plan', sa.Integer(), nullable=True))
    op.add_column('incentive_setting_details', sa.Column('sort_order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incentive_setting_details', 'sort_order')
    op.drop_column('coupon_redemptions', 'bogo_free_plan')
    # ### end Alembic commands ###
